### ISSUE TITLE
SPNP C source code

### ISSUE THREAD

**Issue by Sanahmadi** [aadamvanko/spnp-core#1]
Hello, I wanted to email you, but I could not find an email from you, so I am asking you my questions here. I need SPNP C source codes for university-related work. Do you know what is the way to get these source codes?

**Comment by aadamvanko** [comment]
Hi, you should contact the authors of the SPNP package here https://www2.informatik.uni-hamburg.de/tgi/PetriNets/tools/db/spnp.html or here https://trivedi.pratt.duke.edu/software_packages/spnp . This project generates only the CSPL code from the given Petri Net model, the SPNP package is not included.

Best regards,
Adam
